djangodictionary/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from djangodictionary import settings
from main.views import *

urlpatterns = [

                  path('admin/', admin.site.urls),
                  path('', include('main.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

main/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from main.views import *
from djangodictionary import settings

urlpatterns = [

                  # path('', HomePageView.as_view(), name="home"),
                  path("", HomePageView2.as_view(), name="home2"),
                  path('contact', contact_view, name='contact'),

                  path('about', about_view, name='about'),
                  path("search/", SearchResultsView.as_view(), name="search_results"),
                  path("search2/", SearchResultsView2.as_view(), name="search_results2"),
                  path('contact_view', contact_view, name='contact_view'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models


# Create your models here.


class Word(models.Model):
    name = models.CharField(max_length=50, verbose_name="So'z", db_index=True)
    description = models.TextField(max_length=500, verbose_name="So'z izohi", null=True, blank=True)
    description2 = models.TextField(max_length=500, verbose_name="So'z izohi2", null=True, blank=True)
    description3 = models.TextField(max_length=500, verbose_name="So'z izohi3", null=True, blank=True)
    description4 = models.TextField(max_length=500, verbose_name="So'z izohi4", null=True, blank=True)
    description5 = models.TextField(max_length=500, verbose_name="So'z izohi5", null=True, blank=True)
    description6 = models.TextField(max_length=500, verbose_name="So'z izohi6", null=True, blank=True)
    description7 = models.TextField(max_length=500, verbose_name="So'z izohi7", null=True, blank=True)
    description8 = models.TextField(max_length=500, verbose_name="So'z izohi8", null=True, blank=True)
    description9 = models.TextField(max_length=500, verbose_name="So'z izohi9", null=True, blank=True)
    description10 = models.TextField(max_length=500, verbose_name="So'z izohi10", null=True, blank=True)
    slug = models.SlugField(max_length=200, verbose_name="slug")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "So'z"
        verbose_name_plural = "So'zlar"


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    description = models.TextField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.name

main/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, View
from main.form import *
from .models import Word
from django.http import HttpResponseRedirect

class HomePageView(TemplateView):
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['countWords'] = Word.objects.all().count()
        context['title'] = 'Bosh sahifa'

        return context


class HomePageView2(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['countWords'] = Word.objects.all().count()
        context['title'] = 'Bosh sahifa'

        return context


def contact_view(request):
    return render(request, 'contact.html')


def about_view(request):
    return render(request, 'about.html')


class SearchResultsView(ListView):
    model = Word
    template_name = 'main/index.html'

    # extra_context = {'title': 'Bosh sahifa', 'countWords': Word.objects.all().count()}
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['countWords'] = Word.objects.all().count()
        context['title'] = 'Bosh sahifa'

        return context

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = Word.objects.filter(Q(name=query))
        return object_list


class SearchResultsView2(ListView):
    model = Word
    template_name = 'index.html'

    # extra_context = {'title': 'Bosh sahifa', 'countWords': Word.objects.all().count()}
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['countWords'] = Word.objects.all().count()
        context['title'] = 'Bosh sahifa'

        return context

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = Word.objects.filter(Q(name=query))
        return object_list


# server {
#     listen 80;
#     server_name gippologik-termin.uz;
#
#     location = /favicon.ico { access_log off; log_not_found off; }
#     location /static/ {
#         root /home/ubuntu/nurbek/djangodictionary
# ;
#     }
#
#     location / {
#         include proxy_params;
#         proxy_pass http://unix:/run/sayt.sock;
#     }
# }
def contact_view(request):
    form = ContactForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.META['HTTP_REFERER'])
    else:
        form = ContactForm()
    context = {
        'form': form,
    }
    return render(request, 'contact.html', context)

main/templates/index.html
<!doctype html>
<html lang="en">
{% load static %}
{% load widget_tweaks %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <title>Pod Talk - Free Bootstrap 5 CSS Template</title>

    <!-- CSS FILES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <!--    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400&family=Sono:wght@200;300;400;500;700&display=swap"-->
    <!--          rel="stylesheet">-->
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/templatemo-pod-talk.css'   %} ">


    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">


</head>

<body>

<main>


    <section class="hero-section" style="     margin-bottom: 200px;">

        <nav class="navbar navbar-expand-lg" style="margin-top: -155px; margin-left: 15px;
    margin-bottom: 100px;">
            <div class="container">


                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-lg-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'home2' %}">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'about' %}">About</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                        </li>
                    </ul>


                </div>
            </div>
        </nav>

        <div class="container">
            <div class="row">

                <div class="col-lg-12 col-12">

                    <section class="home" id="home" style="    display: flex;
    flex-direction: column;
    flex-wrap: nowrap;
    align-content: center;
    align-items: center;">


                        <form class="form-inline active-cyan-3 active-cyan-4" action="{% url 'search_results2' %} "
                              method="GET" style="    display: flex;
    flex-direction: column;
    align-items: center;">
                            <div style="display: flex;
    flex-wrap: nowrap;
    align-items: center;">
                                <div class="col">
                                    <i class="fas fa-search" aria-hidden="true"></i>
                                    <input class="form-control form-control-sm ml-3 " type="text"
                                           placeholder="Search"
                                           aria-label="Search"
                                           style=" text-align: center;height:41px; width: 400px; border: 1px solid #000000;border-radius: 3px;"
                                           type="search" id="gsearch" name="q">
                                </div>


                                <div class="col">
                                    <button style="    width: 54px;
    height: 41px;
    border-radius: 3px;" type="submit" value="qidirish" class="btn btn-primary"><i class="bi bi-search"></i></button>
                                </div>
                            </div>

                            <br>
                            <br>


                        </form>

{% for word in word_list %}
                        <h1 style="   border-width: 10px 10px 10px 10px;  border-style: solid dashed solid dashed; background-color: rgb(252 252 252 / 69%);border-color: #3b27b0 #c2c6eb #3b27b0 #c2c6eb; padding: 20px;">
                            <p>
                            <ul>

                                <li>
                                    {% if word.description %}
                                    <h1 style="color: black;"> {{ word.name }} </h1>
                                    <p style="color: black;">{{ word.description }}</p>
                                    {% endif %}
                                    {% if word.description2 %}
                                    <h1 style="color: black;"> {{ word.name }} </h1>
                                    <p style="color: black;">{{ word.description2 }}</p>
                                    {% endif %}
                                    {% if word.description3 %}
                                    <h1 style="color: black;"> {{ word.name }} </h1>
                                    <p style="color: black;">{{ word.description3 }}</p>
                                    {% endif %}
                                    {% if word.description4 %}
                                    <h1 style="color: black;"> {{ word.name }} </h1>
                                    <p style="color: black;">{{ word.description4 }}</p>
                                    {% endif %}
                                    {% if word.description5 %}
                                    <h1 style="color: black;"> {{ word.name }} </h1>
                                    <p style="color: black;">{{ word.description5 }}</p>
                                    {% endif %}
                                    {% if word.description6 %}
                                    <h1 style="color: black;"> {{ word.name }} </h1>
                                    <p style="color: black;">{{ word.description6 }}</p>
                                    {% endif %}
                                    {% if word.description7 %}
                                    <h1 style="color: black;"> {{ word.name }} </h1>
                                    <p style="color: black;">{{ word.description7 }}</p>
                                    {% endif %}
                                    {% if word.description8 %}
                                    <h1 style="color: black;"> {{ word.name }} </h1>
                                    <p style="color: black;">{{ word.description8 }}</p>
                                    {% endif %}
                                    {% if word.description9 %}
                                    <h1 style="color: black;"> {{ word.name }} </h1>
                                    <p style="color: black;">{{ word.description9 }}</p>
                                    {% endif %}
                                    {% if word.description10 %}
                                    <h1 style="color: black;"> {{ word.name }} </h1>
                                    <p style="color: black;">{{ word.description10 }}</p>
                                    {% endif %}
                                </li>

                            </ul>
                            </p>
                        </h1>
                         {% endfor %}
                        <div class="shape"></div>

                    </section>
                </div>


            </div>
        </div>
    </section>


</main>


<footer class="site-footer" style="">
    <div class="container">
        <div class="row">


            <div class="col-lg-3 col-md-6 col-12 mb-4 mb-md-0 mb-lg-0">
                <h6 class="site-footer-title mb-3">Contact</h6>

                <p class="mb-2"><strong class="d-inline me-2">Phone:</strong> 010-020-0340</p>

                <p>
                    <strong class="d-inline me-2">Email:</strong>
                    <a href="#">inquiry@pod.co</a>
                </p>
            </div>

            <div class="col-lg-3 col-md-6 col-12">
                <h6 class="site-footer-title mb-3">Download Mobile</h6>

                <div class="site-footer-thumb mb-4 pb-2">
                    <div class="d-flex flex-wrap">
                        <a href="#">
                            <img src="{% static 'main/img/images/app-store.png' %}" class="me-3 mb-2 mb-lg-0 img-fluid"
                                 alt="">
                        </a>

                        <a href="#">
                            <img src="{% static 'main/img/images/play-store.png' %}" class="img-fluid" alt="">
                        </a>
                    </div>
                </div>

                <h6 class="site-footer-title mb-3">Social</h6>

                <ul class="social-icon">
                    <li class="social-icon-item">
                        <a href="#" class="social-icon-link bi-instagram"></a>
                    </li>

                    <li class="social-icon-item">
                        <a href="#" class="social-icon-link bi-twitter"></a>
                    </li>

                    <li class="social-icon-item">
                        <a href="#" class="social-icon-link bi-whatsapp"></a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-3 col-3">
                <p class="copyright-text mb-0">Copyright © 2036 Talk Pod Company
                    <br><br>
                    Design: <a rel="nofollow" href="https://templatemo.com/page/1" target="_parent">TemplateMo</a></p>
            </div>

        </div>
    </div>

    <div class="container pt-5">
        <div class="row align-items-center">


        </div>
    </div>
</footer>


<!-- JAVASCRIPT FILES -->
<script src=" {% static 'main/js/jquery.min.js' %}"></script>

<script src=" {% static 'main/js/owl.carousel.min.js' %}"></script>
<script src=" {% static 'main/js/custom.js' %}"></script>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
<style>
    .active-pink-2 input[type=text]:focus:not([readonly]) {
  border-bottom: 1px solid #f48fb1;
  box-shadow: 0 1px 0 0 #f48fb1;
}
.active-pink input[type=text] {
  border-bottom: 1px solid #f48fb1;
  box-shadow: 0 1px 0 0 #f48fb1;
}
.active-purple-2 input[type=text]:focus:not([readonly]) {
  border-bottom: 1px solid #ce93d8;
  box-shadow: 0 1px 0 0 #ce93d8;
}
.active-purple input[type=text] {
  border-bottom: 1px solid #ce93d8;
  box-shadow: 0 1px 0 0 #ce93d8;
}
.active-cyan-2 input[type=text]:focus:not([readonly]) {
  border-bottom: 1px solid #4dd0e1;
  box-shadow: 0 1px 0 0 #4dd0e1;
}
.active-cyan input[type=text] {
  border-bottom: 1px solid #4dd0e1;
  box-shadow: 0 1px 0 0 #4dd0e1;
}
.active-cyan .fa, .active-cyan-2 .fa {
  color: #4dd0e1;
}
.active-purple .fa, .active-purple-2 .fa {
  color: #ce93d8;
}






</style>

</body>
</html>

main/templates/main/index.html
<!DOCTYPE html>

{% load static %}
{% load widget_tweaks %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    <!-- google fonts cdn link  -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">

</head>
<body>

<!-- header section starts  -->

<header>

    <div id="menu" class="fas fa-bars"></div>

    <a href="#" class="logo"><i class="fas fa-user-graduate"></i> O'zbek tilidagi gippologik terminlar lug'ati </a>

    <nav class="navbar">
        <ul>
            <li><a class="active" href="#home">Bosh sahifa</a></li>
            <!-- <li><a href="#about">about</a></li>
            <li><a href="#course">course</a></li>
            <li><a href="#teacher">teacher</a></li> -->
            <li><a href="#contact">Bog'lanish</a></li>
            <li><a href="">tizimda {{ countWords }} ta so'z bor!</a></li>
        </ul>
    </nav>

    <div id="login" class="fas fa-user-circle"></div>

</header>

<!-- header section ends -->

<!-- login form  -->

<div class="login-form">

    <form action="">
        <h3>Kirish</h3>
        <input type="email" placeholder="Ismingiz" class="box">
        <input type="password" placeholder="kalit so'z" class="box">
        <p>Kalit so'zni ututdingizmi? <a href="#">Qayta tiklash</a></p>
        <p>Accountingiz yo'qmi? <a href="#">Ro'yhatdan o'tish</a></p>
        <input type="submit" class="btn" value="Kirish">
        <i class="fas fa-times"></i>
    </form>

</div>

<!-- home section starts  -->

<section class="home" id="home">


    <form action="{% url 'search_results' %} " method="GET">
        <input style=" text-align: center;height:41px; width: 400px; border: 1px solid #000000;border-radius: 30px;"
               type="search" id="gsearch" name="q">
        <br><br>
        <!--        <a href="#">-->
        <input type="submit" value="qidirish" class="btn" style="">
        <!--        </a><br>-->
    </form>


    <h1>
        <p>
        <ul>
            {% for word in word_list %}
            <li>
                {{ word.name }} - {{ word.description }}
            </li>
            {% endfor %}
        </ul>
        </p>
    </h1>
    <div class="shape"></div>

</section>

<!-- home section ends -->

<!-- contact section starts  -->

<section class="contact" id="contact">

    <h1 class="heading">Bog'lanish uchun</h1>

    <div class="row">

        <form action="">
            <input type="text" placeholder="ism sharifingiz" class="box">
            <input type="email" placeholder="email" class="box">
            <input type="password" placeholder="kalit so'z" class="box">
            <input type="number" placeholder="number" class="box">
            <textarea name="" id="" cols="30" rows="10" class="box address" placeholder="address"></textarea>
            <input type="submit" class="btn" value="yuborish">
        </form>

        <div class="image">
            <img src="{% static 'main/img/contact-img.png' %} " alt="">
        </div>

    </div>

</section>

<!-- contact section ends -->

<!-- footer section starts  -->

<div class="footer">

    <div class="box-container">

        <div class="box">
            <h3>filial joylari</h3>
            <a href="#">UZ</a>
            <a href="#">USA</a>
            <a href="#">france</a>
            <a href="#">russia</a>
        </div>

        <div class="box">
            <h3>Tezkor havola</h3>
            <a href="#">bosh sahifa</a>
            <!-- <a href="#">about</a>
            <a href="#">course</a>
            <a href="#">teachers</a> -->
            <a href="#">bog'lanish</a>
        </div>

        <div class="box">
            <h3>bog'lanish uchun ma'lumotlar</h3>
            <p><i class="fas fa-map-marker-alt"></i> Termiz, UZB 109108. </p>
            <p><i class="fas fa-envelope"></i> uktamabdunazarov@gmail.com </p>
            <p><i class="fas fa-phone"></i>+998 99 021 25 25 </p>
        </div>

    </div>

    <h1 class="credit">created by <a href="https://t.me/UmarzodaShohruh">Umarzoda</a> all rights reserved. </h1>

</div>

<!-- footer section ends -->


<!-- jquery cdn link  -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!-- custom js file link  -->
<script src=" {% static 'main/js/script.js' %}"></script>

</body>
</html>
<style>
    *{
    text-transform: none;
    }

</style>